[[main]]
  name = "About"
  pageRef = "about"
  weight = 1

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 2

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 3

[[main]]
  name = "Library"
  pageRef = "library"
  weight = 4

[[footer]]
  name = "Technical Book Reviews"
  pageRef = "revisao-tecnica"
  weight = 1
